### ISSUE TITLE
How to handle base-file

### ISSUE THREAD

**Issue by Floppy012** [lucassabreu/comment-coverage-clover#29]
I just started using GitHub Actions and so far I love it. And I would like to use this action. But it's not really clear to me how to handle the `base-file`.

In my case the `base-file` should be the coverage report from the `main` branch. But how do I access that from an action running in a PR? 

* Committing the base coverage report and automating that seems a little strange
* I cannot access artifacts that weren't created in the same workflow

The only option I see would be to use a cache for that. With the only downside being that the cache will be deleted when it's not being accessed for 7 days in a row.

Or is there a better way to handle this?

**Comment by jacekk** [comment]
@Floppy012 I have two actions:

```yml
// .github/workflows/coverage-store.yml
name: Coverage Store

on:
    push:
        branches:
            - develop

permissions:
    actions: write
    contents: read
    packages: read

jobs:
    coverage_store:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: yarn test-ci --coverage

            - name: Upload coverage for current branch
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-reports-artifact
                  path: ./coverage/clover.xml
```

and

```yml
// .github/workflows/coverage-report.yml
name: Coverage Report

on:
    pull_request:
        branches-ignore:
            - 'dependabot/npm_and_yarn/**'

permissions:
    actions: read
    contents: read
    packages: read
    pull-requests: write

jobs:
    coverage_report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: yarn test-ci --coverage

            - name: Download coverage for DEVELOP branch
              uses: dawidd6/action-download-artifact@v2
              continue-on-error: true
              with:
                  branch: develop
                  name: coverage-reports-artifact
                  path: ./coverage/base/
                  search_artifacts: true
                  workflow: .github/workflows/coverage-store.yml
            - name: Coverage Report as Comment (Clover)
              uses: lucassabreu/comment-coverage-clover@v0.9.1
              with:
                  base-file: ./coverage/base/clover.xml
                  chart-size: 90
                  dir-prefix: ${{ github.workspace }}
                  file: ./coverage/clover.xml
                  show-percentage-change-on-table: true
                  table-coverage-change: 0.1
```

I hope this is helpful, as I've also had to figure this thing out :smile:

**Comment by lucassabreu** [comment]
hi @Floppy012 , i do use the action ["dawidd6/action-download-artifact"](https://github.com/dawidd6/action-download-artifact) to download from other branchs (the base branch of the PR). and use "actions/upload-artifact" on the base branchs to upload the "base-file" after the commit.

most of them look something like the yaml bellow.

the important steps are:
- `download_base_file` download a artifact from another branch/workflow
- `upload_base_file` is just a artifact upload for the next time

```yaml
name: Coverage Report

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # next step varies project to project
      - uses: docker://php:7.4 
        env:
          XDEBUG_ENABLED: true
        with:
          args: php ./bin/phpunit -c phpunit.xml --coverage-clover=tests/clover.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: download_base_file
        uses: dawidd6/action-download-artifact@v2.24.0
        continue-on-error: true
        with:
          workflow: .github/workflows/cover-report.yml
          branch: main
          name: clover-coverage
          path: tests/_base

      - if: ${{ github.event_name != 'pull_request' }}
        name: upload_base_file
        uses: actions/upload-artifact@v3
        with:
          name: clover-coverage
          path: tests/clover.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: tests/clover.xml
          base-file: tests/_base/clover.xml
```
