### ISSUE TITLE
Table links to wrong file (folder missing)

### ISSUE THREAD

**Issue by klippx** [lucassabreu/comment-coverage-clover#33]
I have a clover coverage xml on this format
```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1684932596677" clover="3.2.0">
  <project timestamp="1684932596677" name="All files">
    <metrics statements="794" coveredstatements="716" conditionals="252" coveredconditionals="178" methods="130" coveredmethods="106" elements="1176" coveredelements="1000" complexity="0" loc="794" ncloc="794" packages="8" files="24" classes="24"/>
    <package name="create-server">
      <metrics statements="39" coveredstatements="33" conditionals="14" coveredconditionals="7" methods="5" coveredmethods="5"/>
      <file name="response-cache-plugin.ts" path="/Users/MKLIPPIN/repos/graphql-federation-mono/dgs/environmental/create-server/response-cache-plugin.ts">
        <metrics statements="23" coveredstatements="23" conditionals="6" coveredconditionals="5" methods="2" coveredmethods="2"/>
```

I am running the GH Action with this config:
```yaml
    - name: Coverage Report as Comment (Clover)
      uses: lucassabreu/comment-coverage-clover@v0.3.0
      with:
        github-token: '${{ secrets.GH_PAT }}'
        file: ./dgs/${{ inputs.service_name }}/coverage/clover.xml
        dir-prefix-keep: dgs/${{ inputs.service_name }}
```

So if we consider the `path` in clover which in my example is `/Users/MKLIPPIN/repos/graphql-federation-mono` then on CI it should be whatever, maybe it is `/home/runner/work/graphql-federation-mono`.

But when it generates the table all the links are wrong, it is completely missing folder: 
```text
https://github.com/%COMPANY%/graphql-federation-mono/blob/%sha%/dgs/environmental//response-cache-plugin.ts
```
, in this case it is missing the path segment `create-server`.

But if there are multiple levels of folder, it removes them all and replaces with emty string.

What's wrong? Something unexpected in my clover xml?

I have also tried experimenting with `dir-prefix` but not found anything that works.

<img width="664" alt="Screenshot 2023-05-24 at 16 22 18" src="https://github.com/lucassabreu/comment-coverage-clover/assets/2785359/381e9efa-c932-4dd2-a717-a8c636d26824">

This is how my table looks, there is no folder information here either, perhaps a clue? It just appears as a flat structure, which is confusing when a lot of files are called index.ts
