### ISSUE TITLE
Error: this action requires a pull request context to be able to comment https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request 

### ISSUE THREAD

**Issue by lucassabreu** [lucassabreu/comment-coverage-clover#45]
from @AnmolSaxenaVodafone at [here](https://github.com/lucassabreu/comment-coverage-clover/commit/0dd50e6afa8a4964d035052f4bf331b927477e5d#commitcomment-131412811)

---

I am using the below step to generate a Clover report:
```
      # Generate Clover Report
      - name: Generate Clover Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: target/site/clover/clover.xml
          with-chart: false
```
After this commit, I have started getting below exception when I merge the change to the main branch:

```
Error: this action requires a pull request context to be able to comment
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request Stack: undefined
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Generate Clover Report
```
Can you advise if the Generate Clover Report step needs to be updated?
